export const FACILITY = {
  CLEAR_AMENITIES: "FACILITY_CLEAR_AMENITIES",
  PICKED_LOCATION: "FACILITY_PICKED_LOCATION",
  SET_AMENITIES: "FACILITY_SET_AMENITIES",
  SET_LIST: "FACILITY_SET_LIST",
  VALID_REQUEST: "FACILITY_VALID_REQUEST"
};
